# Use lightest Alpine linux
FROM alpine:3.18

# Install lighttpd
RUN apk add --no-cache lighttpd

# Copy index.html to lighttpd default folder
COPY index.html /var/www/localhost/htdocs/index.html
COPY lighttpd.conf /etc/lighttpd/lighttpd.conf

# Expose port 80
EXPOSE 80

# Run lighttpd
# -D: foreground (container stay running)
# -f: specific file configuration
CMD ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]