services:
  postgres:
    image: postgres:16-alpine
    container_name: tw-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shipping_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - tw-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tw-fastapi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shipping_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      tw-network:
        aliases:
          - tw-backend-service

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: tw-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - tw-network

networks:
  tw-network:
    driver: bridge