server.document-root = "/var/www/localhost/htdocs"
server.port           = 80

index-file.names = ( "index.html" )

mimetype.assign = (
    ".html" => "text/html",
    ".css"  => "text/css",
    ".js"   => "application/javascript",
    ".json" => "application/json"
)

server.modules += ( "mod_proxy" )

$HTTP["url"] =~ "^/api" {
    proxy.server = ( "" => (
        ( "host" => "backend", "port" => 8000 )
    ) )
    proxy.header = ( "map-urlpath" => ( "/api" => "" ) )
}