server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Ini kunci agar fetch('/api/get-name') berhasil
    location /api/ {
        proxy_pass http://backend-service:8000/;
        proxy_set_header Host $host;
    }
}