global:
  initial: "tw" # Pastikan 'initial' ada di bawah 'global'

mongodb:
  image: mongo:latest
  port: 27017

backend:
  replicaCount: 2
  image: tw-project-lws-backend
  tag: latest
  port: 8000

frontend:
  replicaCount: 1
  image: tw-project-lws-frontend
  tag: latest
  port: 80