global:
  initial: "tw" # Pastikan 'initial' ada di bawah 'global'

postgres:
  image: postgres:16-alpine
  port: 5432
  storageSize: 1Gi
  db: shipping_db
  auth:
    username: postgres
    password: ""   # isi saat deploy pakai --set, jangan di sini   #isi saat deploy pakai --set

backend:
  replicaCount: 2
  image: tw-project-lws-backend
  tag: latest
  port: 8000

frontend:
  replicaCount: 2
  image: tw-project-lws-frontend
  tag: latest
  port: 80