apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.initial }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: fastapi
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: POSTGRES_HOST
              value: "{{ .Values.global.initial }}-postgres-service"
          envFrom:
            - secretRef:
                name: {{ .Values.global.initial }}-postgres-secret
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.initial }}-backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: {{ .Values.backend.port }}
      nodePort: 30800
