apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shipping-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: shipping.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.initial }}-frontend-service
                port:
                  number: 80
