apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.initial }}-mongodb-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.password | quote }}