apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.initial }}-mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          envFrom:
            - secretRef:
                name: {{ .Values.global.initial}}-mongodb-secret
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ .Values.global.initial }}-mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb  # Ini harus sama persis dengan labels di atas!
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017