apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.initial }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}